#pragma once
#ifndef CONFIGURATION_H
#define CONFIGURATION_H

#define CLI_OUTPUT_BUFFER_SIZE 1024
#define CLI_INPUT_BUFFER_SIZE 60

#define COMM_OUTPUT_BUFFER_SIZE 128
#define COMM_INPUT_BUFFER_SIZE 128
#endif
